// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (
    user_id,
    first_name,
    last_name,
    artist_name,
    photo_url,
    address,
    website_url,
    instagram_handle,
    twitter_handle,
    whatsapp,
    imported_artist_id,
    imported_portal_user_id,
    bio,
    nationality
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, user_id, first_name, last_name, artist_name, photo_url, address, website_url, instagram_handle, twitter_handle, whatsapp, imported_artist_id, imported_portal_user_id, bio, nationality, created_at, updated_at, province, province_code, city, city_code, district, district_code
`

type CreateArtistParams struct {
	UserID               uuid.UUID  `json:"user_id"`
	FirstName            string     `json:"first_name"`
	LastName             string     `json:"last_name"`
	ArtistName           string     `json:"artist_name"`
	PhotoUrl             *string    `json:"photo_url"`
	Address              *string    `json:"address"`
	WebsiteUrl           *string    `json:"website_url"`
	InstagramHandle      *string    `json:"instagram_handle"`
	TwitterHandle        *string    `json:"twitter_handle"`
	Whatsapp             *string    `json:"whatsapp"`
	ImportedArtistID     *uuid.UUID `json:"imported_artist_id"`
	ImportedPortalUserID *uuid.UUID `json:"imported_portal_user_id"`
	Bio                  *string    `json:"bio"`
	Nationality          *string    `json:"nationality"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.ArtistName,
		arg.PhotoUrl,
		arg.Address,
		arg.WebsiteUrl,
		arg.InstagramHandle,
		arg.TwitterHandle,
		arg.Whatsapp,
		arg.ImportedArtistID,
		arg.ImportedPortalUserID,
		arg.Bio,
		arg.Nationality,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.ArtistName,
		&i.PhotoUrl,
		&i.Address,
		&i.WebsiteUrl,
		&i.InstagramHandle,
		&i.TwitterHandle,
		&i.Whatsapp,
		&i.ImportedArtistID,
		&i.ImportedPortalUserID,
		&i.Bio,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Province,
		&i.ProvinceCode,
		&i.City,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
	)
	return i, err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, user_id, first_name, last_name, artist_name, photo_url, address, website_url, instagram_handle, twitter_handle, whatsapp, imported_artist_id, imported_portal_user_id, bio, nationality, created_at, updated_at, province, province_code, city, city_code, district, district_code FROM artists WHERE id = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id uuid.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.ArtistName,
		&i.PhotoUrl,
		&i.Address,
		&i.WebsiteUrl,
		&i.InstagramHandle,
		&i.TwitterHandle,
		&i.Whatsapp,
		&i.ImportedArtistID,
		&i.ImportedPortalUserID,
		&i.Bio,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Province,
		&i.ProvinceCode,
		&i.City,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
	)
	return i, err
}

const getArtistByUserID = `-- name: GetArtistByUserID :one
SELECT id, user_id, first_name, last_name, artist_name, photo_url, address, website_url, instagram_handle, twitter_handle, whatsapp, imported_artist_id, imported_portal_user_id, bio, nationality, created_at, updated_at, province, province_code, city, city_code, district, district_code FROM artists WHERE user_id = $1
`

func (q *Queries) GetArtistByUserID(ctx context.Context, userID uuid.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByUserID, userID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.ArtistName,
		&i.PhotoUrl,
		&i.Address,
		&i.WebsiteUrl,
		&i.InstagramHandle,
		&i.TwitterHandle,
		&i.Whatsapp,
		&i.ImportedArtistID,
		&i.ImportedPortalUserID,
		&i.Bio,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Province,
		&i.ProvinceCode,
		&i.City,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
	)
	return i, err
}

const updateArtistProfile = `-- name: UpdateArtistProfile :one
UPDATE artists
SET
    first_name = $2,
    last_name = $3,
    artist_name = $4,
    photo_url = $5,
    address = $6,
    website_url = $7,
    instagram_handle = $8,
    twitter_handle = $9,
    whatsapp = $10,
    bio = $11,
    province = $12,
    province_code = $13,
    city = $14,
    city_code = $15,
    district = $16,
    district_code = $17,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, first_name, last_name, artist_name, photo_url, address, website_url, instagram_handle, twitter_handle, whatsapp, imported_artist_id, imported_portal_user_id, bio, nationality, created_at, updated_at, province, province_code, city, city_code, district, district_code
`

type UpdateArtistProfileParams struct {
	UserID          uuid.UUID `json:"user_id"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	ArtistName      string    `json:"artist_name"`
	PhotoUrl        *string   `json:"photo_url"`
	Address         *string   `json:"address"`
	WebsiteUrl      *string   `json:"website_url"`
	InstagramHandle *string   `json:"instagram_handle"`
	TwitterHandle   *string   `json:"twitter_handle"`
	Whatsapp        *string   `json:"whatsapp"`
	Bio             *string   `json:"bio"`
	Province        *string   `json:"province"`
	ProvinceCode    *string   `json:"province_code"`
	City            *string   `json:"city"`
	CityCode        *string   `json:"city_code"`
	District        *string   `json:"district"`
	DistrictCode    *string   `json:"district_code"`
}

func (q *Queries) UpdateArtistProfile(ctx context.Context, arg UpdateArtistProfileParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtistProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.ArtistName,
		arg.PhotoUrl,
		arg.Address,
		arg.WebsiteUrl,
		arg.InstagramHandle,
		arg.TwitterHandle,
		arg.Whatsapp,
		arg.Bio,
		arg.Province,
		arg.ProvinceCode,
		arg.City,
		arg.CityCode,
		arg.District,
		arg.DistrictCode,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.ArtistName,
		&i.PhotoUrl,
		&i.Address,
		&i.WebsiteUrl,
		&i.InstagramHandle,
		&i.TwitterHandle,
		&i.Whatsapp,
		&i.ImportedArtistID,
		&i.ImportedPortalUserID,
		&i.Bio,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Province,
		&i.ProvinceCode,
		&i.City,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
	)
	return i, err
}
