// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID                   uuid.UUID  `json:"id"`
	UserID               uuid.UUID  `json:"user_id"`
	FirstName            string     `json:"first_name"`
	LastName             string     `json:"last_name"`
	ArtistName           string     `json:"artist_name"`
	PhotoUrl             *string    `json:"photo_url"`
	Address              *string    `json:"address"`
	WebsiteUrl           *string    `json:"website_url"`
	InstagramHandle      *string    `json:"instagram_handle"`
	TwitterHandle        *string    `json:"twitter_handle"`
	Whatsapp             *string    `json:"whatsapp"`
	ImportedArtistID     *uuid.UUID `json:"imported_artist_id"`
	ImportedPortalUserID *uuid.UUID `json:"imported_portal_user_id"`
	Bio                  *string    `json:"bio"`
	Nationality          *string    `json:"nationality"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	Province             *string    `json:"province"`
	ProvinceCode         *string    `json:"province_code"`
	City                 *string    `json:"city"`
	CityCode             *string    `json:"city_code"`
	District             *string    `json:"district"`
	DistrictCode         *string    `json:"district_code"`
}

type PasswordToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type User struct {
	ID                 uuid.UUID `json:"id"`
	Email              string    `json:"email"`
	PasswordHash       *string   `json:"password_hash"`
	Role               string    `json:"role"`
	Handle             string    `json:"handle"`
	MustChangePassword bool      `json:"must_change_password"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Vendor struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	City         string    `json:"city"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	PicName      *string   `json:"pic_name"`
	Whatsapp     *string   `json:"whatsapp"`
	Address      *string   `json:"address"`
	Province     *string   `json:"province"`
	ProvinceCode *string   `json:"province_code"`
	CityCode     *string   `json:"city_code"`
	District     *string   `json:"district"`
	DistrictCode *string   `json:"district_code"`
	PhotoUrl     *string   `json:"photo_url"`
	Bio          *string   `json:"bio"`
}
