// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_tokens.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUnusedTokenByHash = `-- name: GetUnusedTokenByHash :one
SELECT id, user_id, token_hash, purpose, expires_at, used_at, created_at FROM password_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetUnusedTokenByHash(ctx context.Context, tokenHash string) (PasswordToken, error) {
	row := q.db.QueryRow(ctx, getUnusedTokenByHash, tokenHash)
	var i PasswordToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPasswordToken = `-- name: InsertPasswordToken :one
INSERT INTO password_tokens (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, purpose, expires_at, used_at, created_at
`

type InsertPasswordTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertPasswordToken(ctx context.Context, arg InsertPasswordTokenParams) (PasswordToken, error) {
	row := q.db.QueryRow(ctx, insertPasswordToken,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i PasswordToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUnusedTokens = `-- name: InvalidateUnusedTokens :exec
UPDATE password_tokens
SET used_at = NOW()
WHERE user_id = $1
  AND purpose = $2
  AND used_at IS NULL
`

type InvalidateUnusedTokensParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Purpose string    `json:"purpose"`
}

func (q *Queries) InvalidateUnusedTokens(ctx context.Context, arg InvalidateUnusedTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateUnusedTokens, arg.UserID, arg.Purpose)
	return err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE password_tokens SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTokenUsed, id)
	return err
}
