// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, handle, must_change_password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, role, handle, must_change_password, created_at, updated_at
`

type CreateUserParams struct {
	Email              string  `json:"email"`
	PasswordHash       *string `json:"password_hash"`
	Role               string  `json:"role"`
	Handle             string  `json:"handle"`
	MustChangePassword bool    `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Handle,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Handle,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, handle, must_change_password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Handle,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, email, password_hash, role, handle, must_change_password, created_at, updated_at FROM users WHERE handle = $1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Handle,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, handle, must_change_password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Handle,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPassword = `-- name: SetPassword :exec
UPDATE users
SET password_hash = $2, must_change_password = $3, updated_at = NOW()
WHERE id = $1
`

type SetPasswordParams struct {
	ID                 uuid.UUID `json:"id"`
	PasswordHash       *string   `json:"password_hash"`
	MustChangePassword bool      `json:"must_change_password"`
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	return err
}
