// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendors.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (user_id, name, city)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, city, created_at, updated_at, pic_name, whatsapp, address, province, province_code, city_code, district, district_code, photo_url, bio
`

type CreateVendorParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	City   string    `json:"city"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor, arg.UserID, arg.Name, arg.City)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PicName,
		&i.Whatsapp,
		&i.Address,
		&i.Province,
		&i.ProvinceCode,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
		&i.PhotoUrl,
		&i.Bio,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, user_id, name, city, created_at, updated_at, pic_name, whatsapp, address, province, province_code, city_code, district, district_code, photo_url, bio FROM vendors WHERE id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PicName,
		&i.Whatsapp,
		&i.Address,
		&i.Province,
		&i.ProvinceCode,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
		&i.PhotoUrl,
		&i.Bio,
	)
	return i, err
}

const getVendorByUserID = `-- name: GetVendorByUserID :one
SELECT id, user_id, name, city, created_at, updated_at, pic_name, whatsapp, address, province, province_code, city_code, district, district_code, photo_url, bio FROM vendors WHERE user_id = $1
`

func (q *Queries) GetVendorByUserID(ctx context.Context, userID uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByUserID, userID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PicName,
		&i.Whatsapp,
		&i.Address,
		&i.Province,
		&i.ProvinceCode,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
		&i.PhotoUrl,
		&i.Bio,
	)
	return i, err
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET name = $2,
    city = $3,
    pic_name = $4,
    whatsapp = $5,
    address = $6,
    province = $7,
    province_code = $8,
    city_code = $9,
    district = $10,
    district_code = $11,
    photo_url = $12,
    bio = $13,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, name, city, created_at, updated_at, pic_name, whatsapp, address, province, province_code, city_code, district, district_code, photo_url, bio
`

type UpdateVendorParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Name         string    `json:"name"`
	City         string    `json:"city"`
	PicName      *string   `json:"pic_name"`
	Whatsapp     *string   `json:"whatsapp"`
	Address      *string   `json:"address"`
	Province     *string   `json:"province"`
	ProvinceCode *string   `json:"province_code"`
	CityCode     *string   `json:"city_code"`
	District     *string   `json:"district"`
	DistrictCode *string   `json:"district_code"`
	PhotoUrl     *string   `json:"photo_url"`
	Bio          *string   `json:"bio"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.UserID,
		arg.Name,
		arg.City,
		arg.PicName,
		arg.Whatsapp,
		arg.Address,
		arg.Province,
		arg.ProvinceCode,
		arg.CityCode,
		arg.District,
		arg.DistrictCode,
		arg.PhotoUrl,
		arg.Bio,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PicName,
		&i.Whatsapp,
		&i.Address,
		&i.Province,
		&i.ProvinceCode,
		&i.CityCode,
		&i.District,
		&i.DistrictCode,
		&i.PhotoUrl,
		&i.Bio,
	)
	return i, err
}
